# coding: utf-8

"""
    Employees API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@apigee.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_employee_uuid_delete(self):
        """Test case for employee_uuid_delete

        Delete an Employee with given UUID  # noqa: E501
        """
        pass

    def test_employee_uuid_get(self):
        """Test case for employee_uuid_get

        Get an Employee with given UUID.  # noqa: E501
        """
        pass

    def test_employee_uuid_put(self):
        """Test case for employee_uuid_put

        Update an Employee with given UUID  # noqa: E501
        """
        pass

    def test_root_get(self):
        """Test case for root_get

        Get all Employees  # noqa: E501
        """
        pass

    def test_root_post(self):
        """Test case for root_post

        Create a new Employee  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
