# coding: utf-8

"""
    Employees API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@apigee.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.employees_array_inner import EmployeesArrayInner  # noqa: E501
from swagger_client.rest import ApiException


class TestEmployeesArrayInner(unittest.TestCase):
    """EmployeesArrayInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmployeesArrayInner(self):
        """Test EmployeesArrayInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.employees_array_inner.EmployeesArrayInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
