# coding: utf-8

# flake8: noqa

"""
    Employees API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@apigee.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.employee import Employee
from swagger_client.models.employees_array import EmployeesArray
from swagger_client.models.employees_array_inner import EmployeesArrayInner
from swagger_client.models.employees_array_inner_metadata import EmployeesArrayInnerMetadata
